### ISSUE TITLE
Trim log messages

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#281]
a StormCrawler user reported the following problem when processing [http://lijit.com/robots.txt ](http://lijit.com/robots.txt )

the document consists of one very large JSON doc on a single line; the parser obviously complains about its content and adds the content of the line onto the logs; resulting in the error message below.

This could be avoided if we trimmed the log message to the first N characters.

```
2020-01-30 21:44:25,953 FetcherThread #1165 ERROR Unable to write to stream UDP:localhost:514 for appender syslog: org.apache.logging.log4j.core.appender.AppenderLoggingException: Error flushing stream UDP:localhost:514

2020-01-30 21:44:25,954 FetcherThread #1165 ERROR An exception occurred processing Appender syslog org.apache.logging.log4j.core.appender.AppenderLoggingException: Error flushing stream UDP:localhost:514

        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushDestination(OutputStreamManager.java:272)

        at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:228)

        at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:201)

        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.writeByteArrayToManager(AbstractOutputStreamAppender.java:186)

        at org.apache.logging.log4j.core.appender.SocketAppender.directEncodeEvent(SocketAppender.java:446)

        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)

        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)

        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)

        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)

        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)

        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)

        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)

        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)

        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)

        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)

        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)

        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)

        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)

        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005)

        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1876)

        at org.apache.logging.slf4j.Log4jLogger.warn(Log4jLogger.java:244)

        at crawlercommons.robots.SimpleRobotRulesParser.reportWarning(SimpleRobotRulesParser.java:556)

        at crawlercommons.robots.SimpleRobotRulesParser.parseContent(SimpleRobotRulesParser.java:521)

        at com.digitalpebble.stormcrawler.protocol.RobotRulesParser.parseRules(RobotRulesParser.java:165)

        at com.digitalpebble.stormcrawler.protocol.HttpRobotRulesParser.getRobotRulesSet(HttpRobotRulesParser.java:181)

        at com.digitalpebble.stormcrawler.protocol.RobotRulesParser.getRobotRulesSet(RobotRulesParser.java:175)

        at com.digitalpebble.stormcrawler.protocol.AbstractHttpProtocol.getRobotRules(AbstractHttpProtocol.java:65)

        at com.digitalpebble.stormcrawler.bolt.FetcherBolt$FetcherThread.run(FetcherBolt.java:459)

Caused by: java.io.IOException: Message too long (sendto failed)

        at java.net.PlainDatagramSocketImpl.send(Native Method)

        at java.net.DatagramSocket.send(DatagramSocket.java:693)

        at org.apache.logging.log4j.core.net.DatagramOutputStream.flush(DatagramOutputStream.java:103)

        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushDestination(OutputStreamManager.java:270)

        ... 27 more
```

**Comment by sebastian-nagel** [comment]
I'm working on a fix. See #145 for the same issue with sitemaps.

**Comment by jnioche** [comment]
thanks @sebastian-nagel
