### ISSUE TITLE
[Sitemaps] Avoid calling java.net.URL::equals in equals method of sitemap extension attributes

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#322]
I found one of the sitemaps unit tests hanging when working on a slow network with the following stack:
```
"main" #1 prio=5 os_prio=0 tid=0x00007fdc2400b800 nid=0x1f670 runnable [0x00007fdc2a40f000]
   java.lang.Thread.State: RUNNABLE
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at java.net.InetAddress.getByName(InetAddress.java:1077)
        at java.net.URLStreamHandler.getHostAddress(URLStreamHandler.java:442)
        - locked <0x00000000f75aad30> (a sun.net.www.protocol.http.Handler)
        at java.net.URLStreamHandler.hostsEqual(URLStreamHandler.java:461)
        at java.net.URLStreamHandler.sameFile(URLStreamHandler.java:418)
        at java.net.URLStreamHandler.equals(URLStreamHandler.java:339)
        at java.net.URL.equals(URL.java:888)
        at java.util.Objects.equals(Objects.java:59)
        at crawlercommons.sitemaps.extension.VideoAttributes.equals(VideoAttributes.java:568)
        at org.junit.jupiter.api.AssertionUtils.objectsAreEqual(AssertionUtils.java:189)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at crawlercommons.sitemaps.SiteMapParserExtensionTest.testVideosSitemap(SiteMapParserExtensionTest.java:76)
```

The [URL::equals](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#equals-java.lang.Object-) method is very special as it first looks up the host names of the two URLs to compare the IP addresses. This adds some nondeterminism to the equals method - a string comparison should be sufficient.

Eventually, this method should be added to the forbidden-apis checker.

**Comment by sebastian-nagel** [comment]
@Chaiavi - are you working on this?

**Comment by Chaiavi** [comment]
I can't find the time in the near future, please go ahead and fix it
