### ISSUE TITLE
[Domains] Installation of a gzip-compressed public suffix list from cache breaks EffectiveTldFinder

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#441]
The [Download Plugin for Maven](https://github.com/maven-download-plugin/maven-download-plugin#download-plugin-for-maven) may install a gzip-compressed version of the public suffix list when the list is installed from cache. This may cause successive build runs to fail when EffectiveTldFinder tries to read the compressed public suffix list:

```
$> rm ~/.m2/repository/.cache/download-maven-plugin/*

$> mvn -debug clean package
...
[INFO] --- download-maven-plugin:1.7.1:wget (download-public-suffix-list.dat) @ crawler-commons ---
...
[DEBUG] Putting "https://publicsuffix.org/list/effective_tld_names.dat" into cache
[INFO] Downloading: https://publicsuffix.org/list/effective_tld_names.dat
[INFO] 895/?
...
[INFO] downloaded 286025
...
[INFO] BUILD SUCCESS
...

$> file ~/.m2/repository/.cache/download-maven-plugin/eff*
~/.m2/repository/.cache/download-maven-plugin/effective_tld_names.dat_0bb71ab9b834ca30db12c0ff578f2190: gzip compressed data, max compression, original size modulo 2^32 286025

$> file target/classes/effective_tld_names.dat 
target/classes/effective_tld_names.dat: Public Suffix List data, Unicode text, UTF-8 text

$> mvn -debug clean package
...
[INFO] --- download-maven-plugin:1.7.1:wget (download-public-suffix-list.dat) @ crawler-commons ---
...
[DEBUG] Copying file from cache
...
[ERROR] crawlercommons.domains.PaidLevelDomainTest.testInvalidFQDN -- Time elapsed: 0.156 s <<< ERROR!
java.lang.IllegalArgumentException: java.text.ParseException: A prohibited code point was found in the input^_^@^@^@^@^@^B��v�n�8^L}�w�^C^Z{/@^_
        at java.base/java.net.IDN.toASCIIInternal(IDN.java:274)
        at java.base/java.net.IDN.toASCII(IDN.java:122)
        at java.base/java.net.IDN.toASCII(IDN.java:151)
        at crawlercommons.domains.EffectiveTldFinder$EffectiveTLD.asciiConvert(EffectiveTldFinder.java:572)
...

$> file target/classes/effective_tld_names.dat 
target/classes/effective_tld_names.dat: gzip compressed data, max compression, original size modulo 2^32 286025
```

**Comment by sebastian-nagel** [comment]
Cf. maven-download-plugin/maven-download-plugin#253

**Comment by sebastian-nagel** [comment]
This may affect even automated builds: https://github.com/crawler-commons/crawler-commons/actions/runs/6625652556/job/17997128624?pr=442#step:4:2557

**Comment by rzo1** [comment]
Perhaps downgrade for now?

**Comment by sebastian-nagel** [comment]
> Perhaps downgrade for now?

This looks like the only solution now.
